[package]
name = "noteforge"
version = "1.0.0"
description = "Lightweight desktop text and Markdown editor"
authors = ["tommy4377"]
edition = "2021"
license = "MIT"
repository = "https://github.com/tommy4377/NoteForge"
homepage = "https://github.com/tommy4377/NoteForge"
publish = false

[lib]
name = "noteforge_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2.5.0"
tauri-plugin-dialog = "2.7.0"
tauri-plugin-store = "2.4.2"
tauri-plugin-process = "2.3.1"
notify = "8.2.0"
encoding_rs = "0.8.35"
chardetng = "1.0.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
incremental = false
